name: Deploy to Hostinger VPS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm install
        cd backend && npm install
        
    - name: Build frontend
      run: npm run build
      
    - name: Run tests (if any)
      run: |
        echo "No tests configured yet"
        # Add your test commands here when tests are available
        
    - name: Deploy to Hostinger VPS
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.HOSTINGER_HOST }}
        username: ${{ secrets.HOSTINGER_USERNAME }}
        key: ${{ secrets.HOSTINGER_SSH_KEY }}
        port: ${{ secrets.HOSTINGER_PORT || 22 }}
        script: |
          cd /home/${{ secrets.HOSTINGER_USERNAME }}/startup-village-county
          git pull origin master
          npm run install:all
          npm run build
          pm2 restart startup-village-backend
          sudo systemctl reload nginx
          
    - name: Notify deployment status
      if: always()
      run: |
        echo "Deployment completed with status: ${{ job.status }}"
